#!/usr/bin/env bash

for service in $(cat services.list)
do
	echo  ${service}
done
cleanconsul () {
 consul kv export   |jq .[].key -r |xargs -i{} consul kv delete {}
}


updateconsul () {

for service in $(cat services.list)
do
	echo  ${service}

	DOMAIN=$(echo ${service} | awk -F';' '{ print $1 }')
	SERVICE=$(echo ${service} | awk -F';' '{ print $2 }')
	PORT=$(echo ${service} | awk -F';' '{ print $3 }')
	DEST=$(echo ${service} | awk -F';' '{ print $4 }')
	PROT=$(echo ${service} | awk -F';' '{ print $5 }')

	eppath="traefik/http/routers/${SERVICE}/entrypoints"
	epvalue="http"
	consul kv put $eppath $epvalue

	rulepath="traefik/http/routers/${SERVICE}/rule"
	rulevalue="Host(\`${SERVICE}.${DOMAIN}\`)"
	consul kv put $rulepath $rulevalue

	servicepath="traefik/http/routers/${SERVICE}/service"
	servicevalue="${SERVICE}service"
	consul kv put $servicepath $servicevalue

	lbpath="traefik/http/services/${SERVICE}service/loadBalancer/servers/$DEST/url"
	lbvalue="${PROT}://${DEST}.${DOMAIN}:${PORT}"
	consul kv put $lbpath $lbvalue
done

}

cleanconsul
updateconsul

